version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependency-upgrade"
      - "dependabot"
    # We want to keep compatibility with Maven 3.6.0
    ignore:
      - dependency-name: "org.apache.maven:maven-plugin-api"
      - dependency-name: "org.apache.maven:maven-core"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
