name-template: '$RESOLVED_VERSION'
tag-template: 'smpp-$RESOLVED_VERSION'
categories:
    - title: '🚀 Features'
      labels:
          - 'feature'
    - title: '🐛 Bug Fixes'
      labels:
          - 'bug'
    - title: '🧰 Maintenance'
      label: 'improvement'
    - title: '⚙️ Dependencies'
      label: 'dependency-upgrade'
    - title: '📔 Documentation'
      label: 'documentation'
template: |
    ## What’s Changed

    $CHANGES
