---
language: java
# 
env:
  - MAVEN_VERSION=3.6.3

# We need to make a preliminary installation of the needed
# Maven version cause travis will offer only Maven 3.2.5
install:
  - "mvn -N io.takari:maven:wrapper -Dmaven=${MAVEN_VERSION}"

#
script:
  - "./mvnw --show-version --errors --batch-mode clean verify"

jdk:
 - openjdk8
 - openjdk11
 - openjdk13

cache:
  directories:
  - $HOME/.m2

branches:
  except:
    - gh-pages
